<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "https://testng.org/testng-1.0.dtd">
<suite name="Failed suite [Suite]" guice-stage="DEVELOPMENT">
  <test thread-count="5" name="Test(failed)">
    <classes>
      <class name="com.roofhub.qa.TestCases.OrderPageTest">
        <methods>
          <include name="flush"/>
          <include name="setup"/>
          <include name="verifyplaceorder"/>
          <include name="report"/>
          <include name="appium_server_stop"/>
          <include name="verifyCancelOrder"/>
        </methods>
      </class> <!-- com.roofhub.qa.TestCases.OrderPageTest -->
      <class name="com.roofhub.qa.TestCases.LoginPageTest">
        <methods>
          <include name="verifyloginwithvalidcredentials"/>
          <include name="flush"/>
          <include name="setup"/>
          <include name="report"/>
          <include name="verifylogout"/>
          <include name="appium_server_stop"/>
          <include name="verifyloginwithinvalidcredentials"/>
        </methods>
      </class> <!-- com.roofhub.qa.TestCases.LoginPageTest -->
      <class name="com.roofhub.qa.TestCases.RegisterPageTest">
        <methods>
          <include name="verifyRegistration"/>
          <include name="flush"/>
          <include name="setup"/>
          <include name="report"/>
          <include name="appium_server_stop"/>
        </methods>
      </class> <!-- com.roofhub.qa.TestCases.RegisterPageTest -->
    </classes>
  </test> <!-- Test(failed) -->
</suite> <!-- Failed suite [Suite] -->
